# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=40)),
                ('size', models.CharField(choices=[('XXS', 'DoubleExtraSmall'), ('XS', 'ExtraSmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'ExtraLarge'), ('XXL', 'DoubleExtraLarge')], max_length=3)),
                ('option', models.CharField(choices=[('NA', 'none')], max_length=4)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
