# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_task'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('name', 'color', 'size', 'option')]),
        ),
    ]
