# Generated by Django 2.0.2 on 2018-03-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20171206_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Inventory'),
        ),
    ]
